# Datasource (Railway fallback)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:sa}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=org.h2.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=${PORT:8080}

# GitHub OAuth
spring.security.oauth2.client.registration.github.client-id=Ov23liWONu0KpIcY5y4z


spring.security.oauth2.client.registration.github.client-secret=b1654a967f86805d2f25b351f4422bfde5139317
spring.security.oauth2.client.registration.github.scope=user:email 