spring.config.import=optional:file:.env[.properties]

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mariadb://localhost:${MARIADB_PORT:3307}/${MARIADB_DATABASE:librarydb}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${MARIADB_USER:library}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${MARIADB_PASSWORD:}}
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=${PORT:8080}
spring.security.oauth2.client.registration.github.client-id=${GITHUB_CLIENT_ID:}


spring.security.oauth2.client.registration.github.client-secret=${GITHUB_CLIENT_SECRET:}
spring.security.oauth2.client.registration.github.scope=user:email

library.security.default-password=${DEFAULT_USER_PASSWORD:}
